name: Generate Azure Updates RSS Feed

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-feed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 feedgen pytz

    - name: Run RSS generator script
      run: python azure_rss_generator.py

    - name: Upload RSS feed
      uses: actions/upload-artifact@v2
      with:
        name: azure-updates-feed
        path: azure_updates_feed.xml
        retention-days: 5  # Keeps the artifact for 5 days

    - name: Update latest feed file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        cp azure_updates_feed.xml latest_feed.xml
        git add latest_feed.xml
        git commit -m "Update latest feed" || echo "No changes to commit"
        git push
